In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
l1=[x for x in range(0,10)]

In [4]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
l2=[str(x) for x in l1]

In [6]:
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
l3=[x**2 for x in l1]

In [8]:
l3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [9]:
type(l3)


list

In [10]:
import array

In [11]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [12]:
arr=array.array('i',l3)

In [13]:
arr

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [16]:
arr.reverse()

In [17]:
arr

array('i', [81, 64, 49, 36, 25, 16, 9, 4, 1, 0])

In [19]:
type(arr)

array.array

In [20]:
arr1=array.array('i',[x for x in range(0,10)])# 'i'=integer

In [21]:
arr1

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.array(l3)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
np.array([x+3 for x in l1])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [25]:
np.array([1,2,3,4,5],dtype='str')

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [26]:
np.array([1,2,3,4,5],dtype=float)

array([1., 2., 3., 4., 5.])

In [27]:
np.array([1,2,3,4,5],dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [28]:
m=[[1,2,3],[4,5,6],[7,8,9]] #2D list

In [29]:
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
np.array([range(x,x+3) for x in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
[range(x,x+3) for x in [1,4,7]]

[range(1, 4), range(4, 7), range(7, 10)]

In [32]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [36]:
arr3=np.ones([10,10])

In [37]:
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
arr3[1:9,1:9]=0#1:9= [1][1] se le kar [8][1] and 1:9= [1][1] se le kar [1][8]

In [40]:
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
arr4=np.arange(0,9).reshape(3,3)

In [42]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
arr4[:]=0

In [44]:
arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [46]:
np.eye(3,3)#indentity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.transpose(np.eye(3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])