In [2]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
l1=[x for x in range(0,10)]

In [4]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
l2=[str(x) for x in l1]

In [6]:
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [18]:
l3=[x**2 for x in l1]

In [8]:
l3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [9]:
type(l3)


list

In [13]:
import array

In [14]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating-point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [24]:
arr=array.array?

Init signature: array.array(self, /, *args, **kwargs)
Docstring:     
array(typecode [, initializer]) -> array

Return a new array whose items are restricted by typecode, and
initialized from the optional initializer value, which must be a list,
string or iterable over elements of the appropriate type.

Arrays represent basic values and behave very much like lists, except
the type of objects stored in them is constrained. The type is specified
at object creation time by using a type code, which is a single character.
The following type codes are defined:

    Type code   C Type             Minimum size in bytes
    'b'         signed integer     1
    'B'         unsigned integer   1
    'u'         Unicode character  2 (see note)
    'h'         signed integer     2
    'H'         unsigned integer   2
    'i'         signed integer     2
    'I'         unsigned integer   2
    'l'         signed integer     4
    'L'         unsigned integer   4
    'q'         signed integer     8 

In [21]:
arr

array('f', [0.0, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0])

In [16]:
arr.reverse()

In [17]:
arr

array('i', [81, 64, 49, 36, 25, 16, 9, 4, 1, 0])

In [19]:
type(arr)

array.array

In [20]:
arr1=array.array('i',[x for x in range(0,10)])# 'i'=integer

In [21]:
arr1

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.array(l3)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
np.array([x+3 for x in l1])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [25]:
np.array([1,2,3,4,5],dtype='str')

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [26]:
np.array([1,2,3,4,5],dtype=float)

array([1., 2., 3., 4., 5.])

In [27]:
np.array([1,2,3,4,5],dtype=np.float32)
array.dtype()

array([1., 2., 3., 4., 5.], dtype=float32)

In [28]:
m=[[1,2,3],[4,5,6],[7,8,9]] #2D list

In [29]:
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
np.array([range(x,x+3) for x in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
[range(x,x+3) for x in [1,4,7]]

[range(1, 4), range(4, 7), range(7, 10)]

In [32]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [36]:
arr3=np.ones([10,10])

In [37]:
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
arr3[1:9,1:9]=0#1:9= [1][1] se le kar [8][1] and 1:9= [1][1] se le kar [1][8]

In [40]:
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
arr4=np.arange(0,6).reshape(1,2,3)

In [8]:
arr4

array([[[0, 1, 2],
        [3, 4, 5]]])

In [43]:
arr4[:]=0

In [44]:
arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [46]:
np.eye(3,3)#indentity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.transpose(np.eye(3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.full((6,6),64)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [4]:
np.linspace(0,0.1,5)

array([0.   , 0.025, 0.05 , 0.075, 0.1  ])

In [5]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [6]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x00000117DD4BBBA0>
File:            c:\users\lenovo\desktop\coding\python learning\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value o

In [7]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [8]:
np.random.random(3)

array([0.3947217 , 0.75416326, 0.72784804])

In [9]:
np.random.random((2,2))

array([[0.40371239, 0.17641985],
       [0.84796934, 0.91106541]])

In [10]:
np.random.normal(0,1,10)

array([-0.43759339,  0.01328672,  0.67212557,  0.98330052, -0.31816186,
       -0.21297163, -0.68637005,  1.0806162 , -0.44544022, -0.23101853])

In [11]:
np.random.normal(0,1,(2,2))

array([[ 0.21527372, -0.92185191],
       [-0.80387134,  0.19672401]])

In [12]:
np.random.seed?

Signature:      np.random.seed(seed=None)
Call signature: np.random.seed(*args, **kwargs)
Type:           cython_function_or_method
String form:    <cyfunction seed at 0x00000117DD634930>
Docstring:     
seed(seed=None)

Reseed the singleton RandomState instance.

Notes
-----
This is a convenience, legacy function that exists to support
older code that uses the singleton RandomState. Best practice
is to use a dedicated ``Generator`` instance rather than
the random variate generation methods exposed directly in
the random module.

See Also
--------
numpy.random.Generator

In [13]:
np.random.seed(101)
np.random.random(6)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686])

In [14]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [15]:
np.random.randint(50,100,36)

array([54, 90, 78, 50, 96, 55, 62, 79, 90, 99, 69, 97, 58, 79, 84, 94, 58,
       69, 60, 62, 81, 93, 73, 50, 91, 59, 97, 58, 86, 69, 85, 78, 57, 60,
       89, 88], dtype=int32)

In [16]:
np.random.randn?

Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

In [17]:
arr= np.random.randint(0,100,20)

In [18]:
arr

array([73, 52, 18, 71, 15, 44,  0, 12, 17, 75, 79, 97, 93, 24, 36, 63, 19,
       35, 30, 10], dtype=int32)

In [19]:
arr.ndim

1

In [20]:
arr.size

20

In [21]:
arr.shape

(20,)

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr1=np.random.randint(0,40,10)

In [24]:
arr1

array([39, 20, 27,  8, 22, 26, 23, 37, 22,  9], dtype=int32)

In [25]:
arr1[0]

np.int32(39)

In [26]:
arr1[-1]

np.int32(9)

In [27]:
arr1[:4]

array([39, 20, 27,  8], dtype=int32)

In [28]:
arr1[4:]

array([22, 26, 23, 37, 22,  9], dtype=int32)

In [29]:
arr1[4:7]

array([22, 26, 23], dtype=int32)

In [30]:
arr1[5]=73252

In [31]:
arr1

array([   39,    20,    27,     8,    22, 73252,    23,    37,    22,
           9], dtype=int32)

In [32]:
a1=np.random.randint(0,18,(4,4))

In [33]:
a1

array([[13,  2, 15, 11],
       [10, 17,  3,  3],
       [15, 14,  5,  5],
       [ 6,  7,  5, 14]], dtype=int32)

In [34]:
a1[0,1:4]

array([ 2, 15, 11], dtype=int32)

In [35]:
a1[0,1]

np.int32(2)

In [36]:
a1[0:3,1:3]

array([[ 2, 15],
       [17,  3],
       [14,  5]], dtype=int32)

In [37]:
a1[0:3,1:3]

array([[ 2, 15],
       [17,  3],
       [14,  5]], dtype=int32)

In [38]:
a1[::-1,::-1]

array([[14,  5,  7,  6],
       [ 5,  5, 14, 15],
       [ 3,  3, 17, 10],
       [11, 15,  2, 13]], dtype=int32)

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#shallow copy

In [9]:
a=arr2[1:3,1:3]

In [10]:
a

array([[5, 6],
       [8, 9]])

In [11]:
a[1,1]=19

In [12]:
a

array([[ 5,  6],
       [ 8, 19]])

In [13]:
arr2[1,2]=16
arr2

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8, 19]])

In [14]:
a

array([[ 5, 16],
       [ 8, 19]])

#deepcopy

In [16]:
da=arr2[:2,:2].copy()
da

array([[1, 2],
       [4, 5]])

In [17]:
arr2[0,0]=11
arr2

array([[11,  2,  3],
       [ 4,  5, 16],
       [ 7,  8, 19]])

In [18]:
da

array([[1, 2],
       [4, 5]])

In [19]:
da[1,1]=15
da

array([[ 1,  2],
       [ 4, 15]])

In [20]:
arr2

array([[11,  2,  3],
       [ 4,  5, 16],
       [ 7,  8, 19]])

In [22]:
ar=np.array(range(1,26)).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:

ar2=np.array(range(1,10)).reshape(3,3)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
ar2[0,:].reshape(3,1)

array([[1],
       [2],
       [3]])

In [25]:
t=np.array([1,2,3,4])

In [27]:
n=t.reshape(2,2)
n

array([[1, 2],
       [3, 4]])

In [28]:
n.reshape(1,4)

array([[1, 2, 3, 4]])

In [29]:
n.ravel() # to convert multi dimenstional array into 1D

array([1, 2, 3, 4])

In [30]:
n.ravel?

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [31]:
t=n.flatten() 

In [32]:
t[1]=31084

In [33]:
n

array([[1, 2],
       [3, 4]])

In [34]:
t


array([    1, 31084,     3,     4])

In [35]:
arr2[:,np.newaxis]

array([[[11,  2,  3]],

       [[ 4,  5, 16]],

       [[ 7,  8, 19]]])

#concatenation,joining of two array (MD)

In [36]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

In [37]:
np.concatenate([n,n])

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [38]:
np.concatenate([n,n],axis=1)#axis to specify row=0/column=1

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [39]:
x=np.array([1,2,3])
y=np.array([[4,5,6],[7,8,9]])

In [40]:
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.vstack?

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x00000210DD74A7A0>
File:            c:\users\lenovo\desktop\coding\python learning\lib\site-packages\numpy\_core\shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

dtype 

In [42]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [44]:
ar=np.array(range(1,5)).reshape(2,2)
ar

array([[1, 2],
       [3, 4]])

In [45]:
np.hstack((y,ar))

array([[4, 5, 6, 1, 2],
       [7, 8, 9, 3, 4]])

In [46]:
np.split?

Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x00000210DD8B0FE0>
File:            c:\users\lenovo\desktop\coding\python learning\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

    - ary[:2]
    - ary[2:3]
    - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array

In [47]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x00000210DD8B11C0>
File:            c:\users\lenovo\desktop\coding\python learning\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]
>>> np.vsp

In [48]:
np.hsplit?

Signature:       np.hsplit(ary, indices_or_sections)
Call signature:  np.hsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hsplit at 0x00000210DD8B1120>
File:            c:\users\lenovo\desktop\coding\python learning\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
     

In [105]:
a=np.array(range(1,6))
a

array([1, 2, 3, 4, 5])

In [106]:
np.split(a,5) # (a,5,axis) axis=1 verticalyy split axis=0 horizontaly split

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [107]:
np.split(a,6) #not working because

ValueError: array split does not result in an equal division

In [53]:
np.split(a,[2,4]) # :2 3:4 5:

[array([1, 2]), array([3, 4]), array([5])]

In [56]:
arr=np.array(range(1,26)).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
np.vsplit(arr,[2,3])

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])]

In [59]:
np.hsplit(arr,[2,3])

[array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]])]

In [60]:
np.split(arr,5,axis=1)

[array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]]),
 array([[ 5],
        [10],
        [15],
        [20],
        [25]])]

In [61]:
#universel function = sum mean standard devition sin cos

In [62]:
np.sum(arr,axis=0)

array([55, 60, 65, 70, 75])

In [63]:
np.sum(arr,axis=1)

array([ 15,  40,  65,  90, 115])

In [64]:
np.min(arr)

np.int64(1)

In [66]:
np.max(arr)

np.int64(25)

In [67]:
np.argmin(a) # dimention of min num.

np.int64(0)

In [68]:
i=-4

In [69]:
np.absolute(i)

np.int64(4)

In [70]:
np.abs(i)

np.int64(4)

In [71]:
#np.std() np.var()

In [72]:
#np.prod()  # factorial

## Numpy Ex =1

In [4]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.array(range(10,51))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.array(range(10,51,2))

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
np.array(range(0,9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.random(2)

array([0.62514178, 0.92374067])

In [12]:
np.random.randn(25)

array([-1.29738296e-01, -2.02334896e-01,  4.73858743e-01, -1.69696299e+00,
       -1.85478469e+00, -2.05683270e+00, -8.01813452e-01, -1.57154761e+00,
       -5.28476171e-01,  1.74729716e-01, -1.03679586e+00, -1.43517833e+00,
        1.09630055e+00, -3.76110263e-01, -5.92303291e-01, -1.37622147e-01,
        1.63068150e+00,  8.63963838e-01, -1.50257918e+00,  4.39109738e-01,
        3.67163417e-01,  1.32938559e-02, -1.84731097e-03, -5.34854943e-01,
        7.32398127e-02])

In [13]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [8]:
np.linspace(0.01,2)

array([0.01      , 0.05061224, 0.09122449, 0.13183673, 0.17244898,
       0.21306122, 0.25367347, 0.29428571, 0.33489796, 0.3755102 ,
       0.41612245, 0.45673469, 0.49734694, 0.53795918, 0.57857143,
       0.61918367, 0.65979592, 0.70040816, 0.74102041, 0.78163265,
       0.8222449 , 0.86285714, 0.90346939, 0.94408163, 0.98469388,
       1.02530612, 1.06591837, 1.10653061, 1.14714286, 1.1877551 ,
       1.22836735, 1.26897959, 1.30959184, 1.35020408, 1.39081633,
       1.43142857, 1.47204082, 1.51265306, 1.55326531, 1.59387755,
       1.6344898 , 1.67510204, 1.71571429, 1.75632653, 1.79693878,
       1.83755102, 1.87816327, 1.91877551, 1.95938776, 2.        ])

In [15]:
arr=np.array(range(1,26)).reshape(5,5)

In [16]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [18]:
arr[3,4]

np.int64(20)

In [19]:
arr[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [20]:
arr[4]

array([21, 22, 23, 24, 25])

In [21]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
np.sum(arr)

np.int64(325)

In [23]:
np.sum(arr,axis=0)

array([55, 60, 65, 70, 75])

In [29]:
np.max(arr,axis=1)

array([ 5, 10, 15, 20, 25])

In [30]:
np.min(arr,axis=1)

array([ 1,  6, 11, 16, 21])

In [31]:
np.std(arr,axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [32]:
np.var(arr,axis=1)

array([2., 2., 2., 2., 2.])

In [52]:
array=np.zeros([4,4])

In [53]:
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
array[1:3,1:3]=1

In [57]:
array

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

## Numpy Ex = 2

In [63]:
d1=np.array([1,2,3,4,5])

In [64]:
d2=np.array([[1, 2, 3], [4, 5, 6]])

In [65]:
d3=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [66]:
d1.dtype

dtype('int64')

In [67]:
d2.dtype

dtype('int64')

In [68]:
d3.dtype

dtype('int64')

In [72]:
np.ndim(d1)

1

In [73]:
np.ndim(d2)

2

In [75]:
np.ndim(d3)

3

In [76]:
ad1= np.zeros(12)

In [79]:
ad2= np.ones((2,2))

In [10]:
Math_Marks = np.random.randint(0, 101, size=20)

In [11]:
np.sort(Math_Marks)

array([ 14,  18,  20,  21,  32,  34,  39,  49,  50,  56,  58,  58,  66,
        66,  69,  76,  88,  89,  96, 100], dtype=int32)

In [13]:
np.sort(Math_Marks)[::-1]

array([100,  96,  89,  88,  76,  69,  66,  66,  58,  58,  56,  50,  49,
        39,  34,  32,  21,  20,  18,  14], dtype=int32)

In [84]:
Mark=np.copy(Math_Marks)

In [87]:
Im=np.eye(5)

In [88]:
Im

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
Im.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [90]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [93]:
 new=np.vstack([a, [10,11,12]])

In [94]:
new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [96]:
np.vsplit(new, 4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [97]:
np.hsplit(new,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [99]:
np.sum(np.eye(4),axis=0)

array([1., 1., 1., 1.])

In [108]:
a=np.array([1.2, 3.6, 4.7, 5.1, 8.9])

In [109]:
np.ceil(a)

array([2., 4., 5., 6., 9.])

In [110]:
np.floor(a)

array([1., 3., 4., 5., 8.])

In [111]:
np.round(a, decimals=2)

array([1.2, 3.6, 4.7, 5.1, 8.9])

In [19]:
arr[1,1]=25
arr

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0., 25.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
arr=np.eye(5)

In [17]:
np.min(arr,axis=0)

array([0., 0., 0., 0., 0.])

In [18]:
np.max(arr,axis=0)

array([ 1., 25.,  1.,  1.,  1.])

In [117]:
np.std(arr,axis=0)

array([0.4, 0.4, 0.4, 0.4, 0.4])

In [118]:
np.var(arr,axis=0)

array([0.16, 0.16, 0.16, 0.16, 0.16])

In [119]:
null=np.zeros(10)

In [120]:
null[5] = 200

In [121]:
null

array([  0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.,   0.])

In [122]:
seq=np.arange(100, 151)

In [123]:
seq

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [124]:
seq[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [126]:
np.array(range(0,25)).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
array = np.array([1, 0, 2, 0, 0, 4, 0, 8])

In [27]:
array[np.nonzero(array)]

array([1, 2, 4, 8])

In [135]:
m=np.ones((10, 10))

In [136]:
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [137]:
m[1:9,1:19]=0

In [138]:
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
checkerboard = np.zeros((8, 8), dtype=int)

In [9]:
checkerboard[1::2, ::2] = 1  
checkerboard[::2, 1::2] = 1

In [10]:
checkerboard


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [150]:
m1=np.array(range(0,9)).reshape(3,3)

In [3]:
matrix1 = np.random.randint(0, 10, size=(3, 3))
matrix2 = np.random.randint(0, 10, size=(3, 3))

In [4]:
matrix1 + matrix2

array([[10, 15,  7],
       [16,  7,  7],
       [ 9, 11,  2]], dtype=int32)

In [154]:
matrix1 - matrix2

array([[ 6, -3, -1],
       [ 0, -6,  5],
       [-1, -9,  2]], dtype=int32)

In [5]:
np.multiply(matrix1 , matrix2)

array([[21, 54, 12],
       [63,  6, 10],
       [18, 28,  1]], dtype=int32)

In [6]:
np.matmul(matrix1,matrix2)

array([[ 84, 111,  61],
       [ 36,  77,  35],
       [ 84, 100,  60]], dtype=int32)

In [7]:
matrix1*matrix2

array([[21, 54, 12],
       [63,  6, 10],
       [18, 28,  1]], dtype=int32)

In [11]:
#--------------------------------------------------------

In [ ]:
#1) ciel floot round


In [13]:
ar1=np.random.rand(10)
ar1

array([0.46025312, 0.47662354, 0.74267244, 0.31173693, 0.48070818,
       0.88311287, 0.93729269, 0.29421498, 0.37072908, 0.44176606])

In [34]:
ar2=np.random.randn(1000)
ar2

array([ 1.16875267e+00, -4.53002442e-01,  2.71059112e+00,  1.90660689e-01,
       -9.04571213e-03, -1.32364526e+00, -1.32551835e+00, -7.99558567e-01,
       -3.02493980e-01, -9.74929910e-01,  1.59010254e+00, -5.53541858e-02,
        1.10830386e+00, -7.80877557e-01, -1.09063183e+00,  5.27187890e-02,
        6.53554043e-01, -4.12443960e-01, -2.68114092e+00, -8.75591250e-01,
       -5.90215160e-01,  7.98093162e-01,  6.74153448e-01, -2.42418966e-01,
       -5.46652197e-01, -1.03324346e+00,  2.18021324e-01,  8.04011213e-01,
        3.08619824e-01, -4.63005859e-02, -1.55434729e-01, -4.01979647e-01,
        6.88164570e-01, -5.15912397e-01, -6.03654625e-01, -8.68206356e-01,
       -5.31230821e-01,  1.94376320e-01,  3.03307691e-01, -7.55891579e-01,
        3.66914883e-01, -3.24375884e-01,  1.43981128e+00,  1.11956065e+00,
        7.85040552e-01,  4.24665567e-01, -1.02789377e+00,  1.07164926e+00,
       -5.85161609e-01, -9.74256530e-01,  1.26217782e+00,  9.21356327e-01,
        1.25005353e-01,  

In [35]:
ar1.mean()

np.float64(0.5399109886039454)

In [36]:
ar1.std()

np.float64(0.21939746642066507)

In [37]:
ar2.mean()

np.float64(0.0016959582125941912)

In [38]:
ar2.std()

np.float64(1.0265610941065697)

In [25]:
np.ciel(ar1)

AttributeError: module 'numpy' has no attribute 'ciel'

In [30]:
np.ceil(ar1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.floor(ar1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.round(ar1,2)

array([0.46, 0.48, 0.74, 0.31, 0.48, 0.88, 0.94, 0.29, 0.37, 0.44])

In [43]:
x=np.array([1,2,3])
y=np.array([4,5,6])
x[:,np.newaxis]+y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])