In [1]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'2.2.2'

In [ ]:
#Series=1D,Data Frame=2D

In [9]:
pd.Series?

Init signature:
pd.Series(
    data=None,
    index=None,
    dtype: 'Dtype | None' = None,
    name=None,
    copy: 'bool | None' = None,
    fastpath: 'bool | lib.NoDefault' = <no_default>,
) -> 'None'
Docstring:     
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, \*, \*\*) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series. If data is a dict, argument order is
    maintained.
index : array-like or Index (1d)
    

In [70]:
m=pd.Series(range(1,9))

In [71]:
m.index

RangeIndex(start=0, stop=8, step=1)

In [11]:
ar=[1,2]
ar

[1, 2]

In [16]:
tab=pd.Series(ar,['x','y'])

In [18]:
tab['y']

2

In [19]:
tab

x    1
y    2
dtype: int64

In [22]:
tab.mean()

1.5

In [25]:
tab.min()

1

In [30]:
tab1=pd.Series(['x','y'],ar)
tab1

1    x
2    y
dtype: object

In [29]:
tab2=pd.Series([30,50,40],['Maths','Data Sci.','Calculas'])
tab2

Maths        30
Data Sci.    50
Calculas     40
dtype: int64

In [31]:
tab2.values

array([30, 50, 40], dtype=int64)

In [34]:
tab2.index

Index(['Maths', 'Data Sci.', 'Calculas'], dtype='object')

In [35]:
tab2.index[2]

'Calculas'

In [41]:
dmarks={'kishan':-99,'rudra':-20,'samarth':100}
dmarks

{'kishan': -99, 'rudra': -20, 'samarth': 100}

In [44]:
mark=pd.Series(dmarks)
mark

kishan     -99
rudra      -20
samarth    100
dtype: int64

In [46]:
mark.values

array([-99, -20, 100], dtype=int64)

In [47]:
mark.index

Index(['kishan', 'rudra', 'samarth'], dtype='object')

In [51]:
tab1=pd.Series(index=['x','y'],data=ar)
tab1
display(tab1.values,tab1.index)

array([1, 2], dtype=int64)

Index(['x', 'y'], dtype='object')

In [52]:
tab1=pd.Series(index=['x',2],data=ar)
tab1
display(tab1.values,tab1.index)

array([1, 2], dtype=int64)

Index(['x', 2], dtype='object')

In [56]:
mark

kishan     -99
rudra      -20
samarth    100
dtype: int64

In [55]:
mark[:'rudra']

kishan   -99
rudra    -20
dtype: int64

In [60]:
arr=pd.Series(range(1,10),range(1,10))
arr

1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [61]:
arr[:8]

1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

In [62]:
pd.Series({'Hina':'A+','Diya':'C'})

Hina    A+
Diya     C
dtype: object

In [63]:
#turple and list compriantion

In [3]:
pd.Series((1,2,3,4))

0    1
1    2
2    3
3    4
dtype: int64

In [2]:
pd.Series([x for x in range(1,10)])

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [3]:
pd.DataFrame?


Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [5]:
pd.DataFrame({'Riya':[54,23],'sam':[101,102]},['python','fds'])


Riya  sam
python    54  101
fds       23  102

In [11]:
pd.DataFrame([[23,24,25],[45,46,47]],columns=['A','B','C'],index=['Py','Ds'])

A   B   C
Py  23  24  25
Ds  45  46  47

In [4]:
np.random.seed(7)
marks=pd.DataFrame(np.random.randint(0,30,(3,3)),index=['Sia','Tisha','Riya'],columns=['math','cal','R'])
marks

math  cal   R
Sia      15    4  25
Tisha    22    3  19
Riya     23    7  28

In [5]:
marks.columns

Index(['math', 'cal', 'R'], dtype='object')

In [6]:
marks.values

array([[15,  4, 25],
       [22,  3, 19],
       [23,  7, 28]])

In [7]:
marks.index

Index(['Sia', 'Tisha', 'Riya'], dtype='object')

In [8]:
marks['R']

Sia      25
Tisha    19
Riya     28
Name: R, dtype: int32

In [9]:
marks.loc['Riya']#we will pass label

math    23
cal      7
R       28
Name: Riya, dtype: int32

In [10]:
marks.loc['Riya','math']

23

In [11]:
marks.loc['Riya','math':'R']

math    23
cal      7
R       28
Name: Riya, dtype: int32

In [12]:
marks['Total']=marks['R']+marks['math']+marks['cal']

In [13]:
marks

math  cal   R  Total
Sia      15    4  25     44
Tisha    22    3  19     44
Riya     23    7  28     58

In [14]:
g=[]
for i in marks["Total"]:
    if(i<90):
        g.append('Fail')
    else:
        g.append('Pass')
marks['Grade']=g
marks

math  cal   R  Total Grade
Sia      15    4  25     44  Fail
Tisha    22    3  19     44  Fail
Riya     23    7  28     58  Fail

In [16]:
#indexing and selection
marks[['R','cal']]

R  cal
Sia    25    4
Tisha  19    3
Riya   28    7

In [50]:
marks.iloc? # we will pass index

Type:        property
String form: <property object at 0x00000207A90C5D00>
Docstring:  
Purely integer-location based indexing for selection by position.

.. deprecated:: 2.2.0

   Returning a tuple from a callable is deprecated.

``.iloc[]`` is primarily integer position based (from ``0`` to
``length-1`` of the axis), but may also be used with a boolean
array.

Allowed inputs are:

- An integer, e.g. ``5``.
- A list or array of integers, e.g. ``[4, 3, 0]``.
- A slice object with ints, e.g. ``1:7``.
- A boolean array.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output for indexing (one of the above).
  This is useful in method chains, when you don't have a reference to the
  calling object, but would like to base your selection on
  some value.
- A tuple of row and column indexes. The tuple elements consist of one of the
  above inputs, e.g. ``(0, 1)``.

``.iloc`` will raise ``IndexError`` if a requested indexer is
out-of-bound

In [62]:
marks.iloc[0:2,0:3]

math  cal   R
Sia      15    4  25
Tisha    22    3  19

In [77]:
marks.iloc[:,3]

Sia      44
Tisha    44
Riya     58
Name: Total, dtype: int32

In [76]:
marks.iloc[:,3:4]

Total
Sia       44
Tisha     44
Riya      58

In [71]:
marks.loc['Sia',['cal','R']]

cal     4
R      25
Name: Sia, dtype: object

In [82]:
marks.Total[marks.R>20]

Sia     44
Riya    58
Name: Total, dtype: int32

In [83]:
marks[marks.R>20].index

Index(['Sia', 'Riya'], dtype='object')

In [84]:
marks[marks['R']<20]

math  cal   R  Total Grade
Tisha    22    3  19     44  Fail

In [3]:
np.random.seed(2)
Marks=pd.DataFrame(np.random.randint(0,100,(10,3)),index=['s','a','m','a','r','t','h','s','a','r'],columns=['Math','Phy','Py'])
Marks

Math  Phy  Py
s    40   15  72
a    22   43  82
m    75    7  34
a    49   95  75
r    85   47  63
t    31   90  20
h    37   39  67
s     4   42  51
a    38   33  58
r    67   69  88

In [6]:
Marks.Math[Marks.Math<40]=41

C:\Users\SAMARTH\AppData\Local\Temp\ipykernel_10256\783743233.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Marks.Math[Marks.Math<40]=41


In [7]:
Marks

Math  Phy  Py
s    40   15  72
a    41   43  82
m    75    7  34
a    49   95  75
r    85   47  63
t    41   90  20
h    41   39  67
s    41   42  51
a    41   33  58
r    67   69  88

In [8]:
## Pandas Assignment

In [45]:
#1
df = pd.DataFrame({"ProductId": [101, 102, 103, 104, 105],"ProductName": ["Laptop", "Smartphone", "Headphones", "Monitor", "Keyboard"],
"ProductPrice":  [999.99, 499.99, 89.99, 199.99, 29.99]})
df

ProductId ProductName  ProductPrice
0        101      Laptop        999.99
1        102  Smartphone        499.99
2        103  Headphones         89.99
3        104     Monitor        199.99
4        105    Keyboard         29.99

In [46]:
#2
df.ProductPrice+500

0    1499.99
1     999.99
2     589.99
3     699.99
4     529.99
Name: ProductPrice, dtype: float64

In [49]:
#6
for i in range(len(df)):
    print(i)
    print(df.iloc[i])
    print()

0
ProductId          101
ProductName     Laptop
ProductPrice    999.99
Name: 0, dtype: object

1
ProductId              102
ProductName     Smartphone
ProductPrice        499.99
Name: 1, dtype: object

2
ProductId              103
ProductName     Headphones
ProductPrice         89.99
Name: 2, dtype: object

3
ProductId           104
ProductName     Monitor
ProductPrice     199.99
Name: 3, dtype: object

4
ProductId            105
ProductName     Keyboard
ProductPrice       29.99
Name: 4, dtype: object



In [48]:
#6
for i in df.index:
    print(i)
    print(df.loc[i])
    print()

0
ProductId          101
ProductName     Laptop
ProductPrice    999.99
Name: 0, dtype: object

1
ProductId              102
ProductName     Smartphone
ProductPrice        499.99
Name: 1, dtype: object

2
ProductId              103
ProductName     Headphones
ProductPrice         89.99
Name: 2, dtype: object

3
ProductId           104
ProductName     Monitor
ProductPrice     199.99
Name: 3, dtype: object

4
ProductId            105
ProductName     Keyboard
ProductPrice       29.99
Name: 4, dtype: object



In [56]:
#7
df.loc[2]

ProductId              103
ProductName     Headphones
ProductPrice         89.99
Name: 2, dtype: object

In [58]:
#8
df.iloc[1]['ProductPrice']

499.99

In [63]:
#9
df.loc[1:3]-['ProductPrice']

ValueError: Unable to coerce to Series, length must be 3: given 1

In [2]:
#------------------

In [90]:
rng=np.random.RandomState(42)
rng


RandomState(MT19937) at 0x1C81D5C0C40

In [57]:
ser=pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [21]:
df=pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [22]:
np.exp(ser)#exponecial

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [29]:
np.sin(df*np.pi/4)#sin(x)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [32]:
area=pd.Series({'UP':243286,'Maharashtra':307713,'Bihar':94163},name='area')
area

UP             243286
Maharashtra    307713
Bihar           94163
Name: area, dtype: int64

In [37]:
population = pd.Series({'West Bangal':91276115,'Maharashtra':124484447,'Bihar':104099452},name='population')
population

West Bangal     91276115
Maharashtra    124484447
Bihar          104099452
Name: population, dtype: int64

In [38]:
population_density=population/area
population_density

Bihar          1105.523953
Maharashtra     404.547247
UP                     NaN
West Bangal            NaN
dtype: float64

In [40]:
A=pd.Series([2,4,6],index=[0,1,2])
A

0    2
1    4
2    6
dtype: int64

In [41]:
B=pd.Series([1,3,5],index=[1,2,3])
B

1    1
2    3
3    5
dtype: int64

In [42]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [43]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [46]:
A=pd.DataFrame(rng.randint(0,15,(2,2)),columns=list('AB'))
A

A   B
0   6   3
1  12  14

In [47]:
B=pd.DataFrame(rng.randint(0,10,(3,3)),columns=list('BAC'))
B

B  A  C
0  7  4  6
1  9  2  6
2  7  4  3

In [48]:
A+B

A     B   C
0  10.0  10.0 NaN
1  14.0  23.0 NaN
2   NaN   NaN NaN

In [50]:
A.add(B,fill_value=A.stack().mean())

A      B      C
0  10.00  10.00  14.75
1  14.00  23.00  14.75
2  12.75  15.75  11.75

In [51]:
A.stack().mean()

8.75

In [53]:
np.random.seed(10)
np.random.randint(0,10,(2,2))

array([[9, 4],
       [0, 1]])

In [91]:
 rng.rand(3,3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [92]:
 rng.rand(3,3)

array([[0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643]])

In [85]:
X

array([[0.94220176, 0.56328822, 0.3854165 ],
       [0.01596625, 0.23089383, 0.24102547],
       [0.68326352, 0.60999666, 0.83319491]])

In [86]:
Y= rng.rand(3,3)

In [87]:
Y

array([[0.17336465, 0.39106061, 0.18223609],
       [0.75536141, 0.42515587, 0.20794166],
       [0.56770033, 0.03131329, 0.84228477]])

In [62]:
X

array([[6, 9, 2],
       [6, 7, 4],
       [3, 7, 7]])

In [82]:
Z=np.random.rand(3,3)

In [83]:
Z

array([[0.55964837, 0.33549965, 0.41118255],
       [0.0768555 , 0.85304299, 0.43998746],
       [0.12195415, 0.73173462, 0.13878247]])

In [65]:
Z

array([[9, 0, 1],
       [8, 9, 0],
       [8, 6, 4]])

In [68]:
A=np.random.randint(10,size=(3,4))
A

array([[3, 9, 6, 9],
       [1, 9, 4, 2],
       [6, 7, 8, 8]])

In [69]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-2,  0, -2, -7],
       [ 3, -2,  2, -1]])

In [70]:
df = pd.DataFrame(A,columns=list('QRST'))
df

Q  R  S  T
0  3  9  6  9
1  1  9  4  2
2  6  7  8  8

In [71]:
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -2  0 -2 -7
2  3 -2  2 -1

In [72]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -6  0 -3  0
1 -8  0 -5 -7
2 -1  0  1  1

In [74]:
halfrow=df.iloc[0,::2]
halfrow

Q    3
S    6
Name: 0, dtype: int32

In [75]:
df-halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -2.0 NaN -2.0 NaN
2  3.0 NaN  2.0 NaN

In [76]:
df


Q  R  S  T
0  3  9  6  9
1  1  9  4  2
2  6  7  8  8

In [11]:
vals1=np.array([1,None,2,3])
vals1

array([1, None, 2, 3], dtype=object)

In [6]:
%timeit np.arange(1E6,dtype=int).sum()#1E6= 1 x 10^6?

1.86 ms ± 78.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
%timeit np.arange(1E6,dtype=object).sum()

62 ms ± 1.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [14]:
vals2=np.array([1,np.nan,3,4])
vals2

array([ 1., nan,  3.,  4.])

In [20]:
vals2.sum(),vals2.max(),vals2.min(),vals2.mean()

(nan, nan, nan, nan)

In [19]:
np.nansum(vals2),np.nanmax(vals2),np.nanmin(vals2),np.nanmean(vals2)

(8.0, 4.0, 1.0, 2.6666666666666665)

In [22]:
pd.Series([1,np.nan,2,None,pd.NA],dtype='Int32')#Int32 mean there is null value , int32 mean there is not a single null value

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [23]:
np.arange(100,dtype=object)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=object)

In [27]:
#isnull,notnull,dropna,fillna


In [29]:
data=pd.Series([1,np.nan,'hello',None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [30]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [31]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [32]:
data.dropna()

0        1
2    hello
dtype: object

In [35]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [37]:
df=pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [38]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [39]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [40]:
df[3]=np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [44]:
df.dropna(axis='columns',how='all')#column which has all nan value will be drop out

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [45]:
df.dropna(axis='rows',thresh=3)#row me minimum 3 nan hoga to ye use drop kar de ga

0    1  2   3
1  2.0  3.0  5 NaN

In [46]:
data=pd.Series([1,np.nan,2,None,3],index=list('abcde'),dtype='Int32')
data

a       1
b    <NA>
c       2
d    <NA>
e       3
dtype: Int32

In [47]:
data.fillna(0)

a    1
b    0
c    2
d    0
e    3
dtype: Int32

In [48]:
data.fillna(method='ffill')#ffill=forward fill #you can also use nn.ffill()

C:\Users\SAMARTH\AppData\Local\Temp\ipykernel_9568\1161566231.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')#ffill=forward fill


a    1
b    1
c    2
d    2
e    3
dtype: Int32

In [49]:
data.fillna(method='bfill')#nn.bfill()

C:\Users\SAMARTH\AppData\Local\Temp\ipykernel_9568\1397359497.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


a    1
b    2
c    2
d    3
e    3
dtype: Int32

In [50]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [55]:
df.fillna(method='ffill',axis=1)#0=column,1=row

C:\Users\SAMARTH\AppData\Local\Temp\ipykernel_9568\1265886752.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',axis=1)#0=column,1=row


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [52]:
df.fillna(method='bfill',axis=1)

C:\Users\SAMARTH\AppData\Local\Temp\ipykernel_9568\3381026564.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill',axis=1)


0    1    2   3
0  1.0  2.0  2.0 NaN
1  2.0  3.0  5.0 NaN
2  4.0  4.0  6.0 NaN